# Tensorflow Dataset 시작하기

### tensorflow_datasets.load 의 반환값

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/3.0.1.incomplete05MW30/fashion_mnist-train.tfrecord*...:   0…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/3.0.1.incomplete05MW30/fashion_mnist-test.tfrecord*...:   0%…

Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
train
test


### 실제 데이터를 담은 데이터셋 분할 : PrefetchDataset 객체

In [ ]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


### 레코드 가져오기

In [ ]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


데이터 값 확인  
Image : tf.Tensor 타입, 28 x 28, 0 ~ 255

In [ ]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


데이터 셋에 대한 정보

In [ ]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='/root/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    

# keras 모델에서 Tensorflow dataset 사용

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist = tf.keras.datasets.fashion_mnist

(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

### 반환값
keras dataset → ndarray  
tensorflow dataset → Dataset object or Tensor → numpy 배열로 변환 필요

In [ ]:
# batch_size = 1 : 모든 데이터를 가져옴
# as_supervised=True : (input, label) 튜플 반환
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split = ['train', 'test'], batch_size=-1, as_supervised=True))

### Input size
keras dataset → (28, 28)  
Tensorflow dataset → (28, 28, 1)  

In [ ]:
(training_images, training_labels), (test_images, test_labels) = tfds.load('fashion_mnist', split = ['train', 'test'], batch_size=-1, as_supervised=True)

# fashoin_mnist의 경우 tf.uint8 타입의 Tensor가 반환되기 때문에 픽셀값을 255로 나누어 실수로 변환
training_images = tf.cast(training_images, tf.float32) / 255.0
test_images = tf.cast(test_images, tf.float32) / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.5308 - accuracy: 0.8109
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4010 - accuracy: 0.8533
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3686 - accuracy: 0.8660
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3482 - accuracy: 0.8714
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3282 - accuracy: 0.8799


### Horse - Human dataset

In [ ]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True) 

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_batches, epochs=10)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1027 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/3.0.0.incomplete8OZFPC/horses_or_humans-train.tfrecord*..…

Generating test examples...:   0%|          | 0/256 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/3.0.0.incomplete8OZFPC/horses_or_humans-test.tfrecord*...…

Dataset horses_or_humans downloaded and prepared to /root/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/10
103/103 [==============================] - 13s 43ms/step - loss: 2.4296 - accuracy: 0.8578
Epoch 2/10
103/103 [==============================] - 2s 19ms/step - loss: 0.1145 - accuracy: 0.9708
Epoch 3/10
103/103 [==============================] - 2s 18ms/step - loss: 0.0903 - accuracy: 0.9747
Epoch 4/10
103/103 [==============================] - 2s 19ms/step - loss: 0.0123 - accuracy: 0.9951
Epoch 5/10
103/103 [==============================] - 2s 18ms/step - loss: 3.2818e-04 - accuracy: 1.0000
Epoch 6/10
103/103 [==============================] - 2s 18ms/step - loss: 1.2797e-04 - accuracy: 1.0000
Epoch 7/10
103/103 [==============================] - 2s 18ms/step - loss: 7.0294e-05 - accuracy: 1.0000
Epoch 8/10
103/103 [==============================] - 2s 18ms/step - loss: 4.5402e-05 - accuracy: 1.0000
Epoch 9/10
103/103 [==============

### Train 하는 동안 모델 Validation 하기

In [ ]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

validation_batches = val_data.batch(32)

model.fit(train_batches, epochs=10, validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 3s 31ms/step - loss: 1.8605e-05 - accuracy: 1.0000 - val_loss: 3.6341 - val_accuracy: 0.8555
Epoch 2/10
103/103 [==============================] - 2s 20ms/step - loss: 1.4759e-05 - accuracy: 1.0000 - val_loss: 3.6606 - val_accuracy: 0.8594
Epoch 3/10
103/103 [==============================] - 2s 20ms/step - loss: 1.2082e-05 - accuracy: 1.0000 - val_loss: 3.6859 - val_accuracy: 0.8594
Epoch 4/10
103/103 [==============================] - 2s 20ms/step - loss: 9.8238e-06 - accuracy: 1.0000 - val_loss: 3.7643 - val_accuracy: 0.8555
Epoch 5/10
103/103 [==============================] - 2s 20ms/step - loss: 8.1919e-06 - accuracy: 1.0000 - val_loss: 3.8082 - val_accuracy: 0.8555
Epoch 6/10
103/103 [==============================] - 2s 20ms/step - loss: 6.8442e-06 - accuracy: 1.0000 - val_loss: 3.8367 - val_accuracy: 0.8594
Epoch 7/10
103/103 [==============================] - 2s 20ms/step - loss: 5.8446e-06 - accuracy: 1.0000 - val_loss: 3

### 특정 버전 Dataset Load

In [ ]:
data, info = tfds.load("horses_or_humans:3.0.0", with_info=True)

# Mapping function for Image Augmentation

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

data = tfds.load('horses_or_humans', split='train', as_supervised=True)

train_batches = data.shuffle(100).batch(10)

### Mapping 함수 만들기

In [ ]:
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    return image, label

In [ ]:
train = data.map(augmentimages)     # Data에 매핑해 새로운 데이터셋 train 생성

train_batches = train.shuffle(100).batch(32)    # train에서 batch 생성

### Tensorflow Addons 사용
Image Augmentation에 사용할 수 있는 함수 많음

In [2]:
!pip install tensorflow-addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 54.8 MB/s eta 0:00:00


augmentimages 함수에 rotate 추가

In [ ]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

# 사용자 정의 분할

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

tfds.image_classification.cats_vs_dogs._URL = "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"

### train 분할 세트 전체 요청

In [ ]:
data = tfds.load('cats_vs_dogs', split='train', as_supervised=True)

train의 처음 1만 개의 레코드를 train data 로 사용

In [ ]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

처음부터 20%의 분량

In [ ]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

처음 1000개 + 마지막 1000개

In [ ]:
data = tfds.load('cats_vs_dogs', split='train[-1000:] + train[:1000]', as_supervised=True)

### Train, Test, Validation 으로 데이터 나누기

In [ ]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', as_supervised=True)             # 80%

validation_data = tfds.load('cats_vs_dogs', split='train[80%:90%]', as_supervised=True)     # 10%

test_data = tfds.load('cats_vs_dogs', split='train[-10%:]', as_supervised=True)             # 10%

반환된 데이터셋은 길이 정보를 제공하지 않기 때문에 원본 세트를 올바르게 나누었는지 확인하는 것이 어렵다.  
  
얼마나 많은 레코드가 분할 세트에 포함되었는지 확인하려면 전체 세트를 돌면서 하나씩 카운트해야 한다.

In [ ]:
train_length = [i for i,_ in enumerate(train_data)][-1] + 1
print(train_length)

18610


tf.data.experimental.cardinality 함수를 사용해 dataset 길이 카운트할 수 있다.

이 함수는 tf.int64 타입의 Tensor를 반환하므로 numpy 타입으로 변환 후 출력 가능하다.

In [ ]:
print(tf.data.experimental.cardinality(train_data).numpy())

print(tf.data.experimental.cardinality(validation_data).numpy())

print(tf.data.experimental.cardinality(test_data).numpy())

18610
2326
2326


fashion_mnist 처럼 미리 분할된 데이터셋은 with_info=True 로 지정해 분할 세트의 크기를 확인할 수 있다.

In [ ]:
train_data, info = tfds.load('fashion_mnist', with_info=True)

print(info.splits['train'].num_examples, info.splits['test'].num_examples)

60000 10000


# TFRecord

Tensorflow dataset 은 데이터를 다운로드한 다음 디스크에 캐싱한다. 따라서 사용할 때마다 데이터를 다운로드하지 않는다.

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

data, info = tfds.load("mnist", with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_path='/root/tensorflow_datasets/mnist/3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
)


위의 결과를 보면 **file_format=tfrecord** 라고 되어있는 것을 확인할 수 있다.  
이는 Tensorflow 에서 대용량의 데이터를 저장하고 추출할 때 선호하는 포맷이다.

# 데이터 관리를 위한 ETL process



ETL : 규모와는 상관없이 Tensorflow 의 훈련에 사용되는 핵심 패턴  
1. 추출 단계 (Extract phase)  
    다른 곳에 저장되어 있는 원시 데이터를 가져와 변환을 위해 준비  

2. 변환 단계 (Transform phase)  
    훈련이 잘 되도록 데이터를 조작  

3. 로드 단계 (Load phase)  
    훈련을 위해 신경망에 데이터를 로드

In [1]:
!pip install tensorflow-addons

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# 모델 정의
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='Adam', loss='binary_crossentropy', 
              metrics=['accuracy'])

# 추출 단계
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

# 변환 단계
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)
validation_batches = val_data.batch(32)

# 로드 단계 
history = model.fit(train_batches, epochs=10, validation_data=validation_batches)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 16.7 MB/s eta 0:00:00


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1027 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/3.0.0.incompleteTQLJG2/horses_or_humans-train.tfrecord*..…

Generating test examples...:   0%|          | 0/256 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/3.0.0.incompleteTQLJG2/horses_or_humans-test.tfrecord*...…

Dataset horses_or_humans downloaded and prepared to /root/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/10
33/33 [==============================] - 21s 331ms/step - loss: 0.4723 - accuracy: 0.7790 - val_loss: 308.1357 - val_accuracy: 0.6328
Epoch 2/10
33/33 [==============================] - 9s 255ms/step - loss: 0.2759 - accuracy: 0.8861 - val_loss: 317.7140 - val_accuracy: 0.4297
Epoch 3/10
33/33 [==============================] - 9s 251ms/step - loss: 0.0938 - accuracy: 0.9708 - val_loss: 604.5306 - val_accuracy: 0.4414
Epoch 4/10
33/33 [==============================] - 9s 254ms/step - loss: 0.0587 - accuracy: 0.9805 - val_loss: 389.6307 - val_accuracy: 0.4766
Epoch 5/10
33/33 [==============================] - 13s 387ms/step - loss: 0.0419 - accuracy: 0.9873 - val_loss: 401.2030 - val_accuracy: 0.5547
Epoch 6/10
33/33 [==============================] - 9s 253ms/step - loss: 0.0515 - accuracy: 0.9834 - val_loss: 263.1003 - val_accuracy: 

데이터 추출과 변환은 CPU를 포함해 어느 프로세서에서도 수행할 수 있다.  

GPU/TPU는 데이터 다운로드, 압축 해제, 레코드 순회 처리와 같은 단계에서 사용하기 위해 만들어진 것이 아니다.  

따라서 추출과 변환은 CPU에서, 로드 단계는 GPU/TPU 에서 수행하도록 분배해야 한다.


### 추출 단계 병렬화

훈련 속도 향상을 위해 ETL 병렬화

In [2]:
train_data = tfds.load('cats_vs_dogs', split='train', with_info=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/23262 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/cats_vs_dogs/4.0.0.incomplete4JENIO/cats_vs_dogs-train.tfrecord*...:   0%|…

Dataset cats_vs_dogs downloaded and prepared to /root/tensorflow_datasets/cats_vs_dogs/4.0.0. Subsequent calls will reuse this data.


나눠져 있는 TFRecord 파일 가져오기

In [3]:
import sys

if 'google.colab' in sys.modules:
    file_pattern = '/root/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
else:
    file_pattern = os.path.join(
        os.path.expanduser('~') + '/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
    )
files = tf.data.Dataset.list_files(file_pattern)

- cycle_length 

    동시에 전처리할 입력 원소 개수  
    지정하지 않으면 사용 가능한 CPU 코어 개수 사용 

- num_parallel_calls  

    병렬 실행 횟수  
    tf.data.experimental.AUTOTUNE → CPU 개수에 따라 동적으로 설정되기 때문에 코드 이식성 좋아짐  

ex) cycle_length = 4, num_parallel_calls = 6  → 6개의 스레드가 각각 4개의 레코드를 동시에 로딩한다

In [4]:
train_dataset = files.interleave(
    tf.data.TFRecordDataset, 
    cycle_length=4,
    num_parallel_calls=tf.data.experimental.AUTOTUNE
)

### 변환 단계 병렬화

원시 TFRecord 파일을 로드하고 적절한 형태로 바꾸는 매핑 함수 만들기

In [5]:
def read_tfrecord(serialized_example):
    feature_description={
        "image": tf.io.FixedLenFeature((), tf.string, ""),
        "label": tf.io.FixedLenFeature((), tf.int64, -1),
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

In [6]:
import multiprocessing

cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
# 코랩의 경우 데이터셋을 캐싱하면 메모리 부족으로 런타임이 다운될 수 있으므로 주석처리
# train_dataset = train_dataset.cache()

2


### 로드 단계 병렬화

In [7]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

model.fit(train_dataset, epochs=10, verbose=1)

Epoch 1/10
727/727 [==============================] - 74s 97ms/step - loss: 0.6624 - accuracy: 0.6011
Epoch 2/10
727/727 [==============================] - 64s 86ms/step - loss: 0.5420 - accuracy: 0.7276
Epoch 3/10
727/727 [==============================] - 63s 84ms/step - loss: 0.4547 - accuracy: 0.7869
Epoch 4/10
727/727 [==============================] - 62s 84ms/step - loss: 0.3908 - accuracy: 0.8233
Epoch 5/10
727/727 [==============================] - 62s 83ms/step - loss: 0.3340 - accuracy: 0.8530
Epoch 6/10
727/727 [==============================] - 61s 82ms/step - loss: 0.2815 - accuracy: 0.8786
Epoch 7/10
727/727 [==============================] - 62s 83ms/step - loss: 0.2241 - accuracy: 0.9080
Epoch 8/10
727/727 [==============================] - 62s 82ms/step - loss: 0.1729 - accuracy: 0.9300
Epoch 9/10
727/727 [==============================] - 63s 85ms/step - loss: 0.1140 - accuracy: 0.9564
Epoch 10/10
727/727 [==============================] - 61s 82ms/step - loss: 0.079